# Placeholder YAML pipeline for Online Bus Pass Application System

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo 'Placeholder: Installing dependencies...'
  displayName: 'Install dependencies'

- script: echo 'Placeholder: Running tests...'
  displayName: 'Run tests'

- script: echo 'Placeholder: Building application...'
  displayName: 'Build application'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Archive build artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    artifactName: 'drop'
  displayName: 'Publish build artifacts'

- script: echo 'Placeholder: Deploying to test environment...'
  displayName: 'Deploy to test environment'
