name: Python CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Zip Artifact for Deployment
        run: zip -r python-app.zip ./*

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: python-app.zip

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Test Dependencies
        run: pip install -r requirements-test.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v2
        with:
          name: python-app

      - name: Unzip Artifact for Deployment
        run: unzip -o python-app.zip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python Application Locally
        run: |
          python app.py
